import { describe, expect, test } from "bun:test";
import { AdapterRegistry } from "../src/control/adapter-registry";
import { CanonicalEventFeed } from "../src/control/event-feed";
import { TaskQueue } from "../src/control/task-queue";
import { applyRetention } from "../src/control/retention";
import { AlertEngine } from "../src/control/alerts";
import { newId } from "../packages/contracts/src/ids";
import { claimedTask, SHA256, task, trace } from "./fixtures";

describe("canonical control-plane primitives", () => {
  test("task enqueue is repository-scoped and exactly once", () => { const queue = new TaskQueue(); const first = queue.enqueue(task()); const second = queue.enqueue(task({ taskId: newId("task") })); expect(first.duplicate).toBeFalse(); expect(second.duplicate).toBeTrue(); });
  test("same dedupe key is independent across repositories", () => { const queue = new TaskQueue(); queue.enqueue(task()); const other = task({ taskId: newId("task"), repo: "other/project", consentScope: { ...task().consentScope, repo: "other/project" } }); expect(queue.enqueue(other).duplicate).toBeFalse(); });
  test("only one runtime claims a task", () => { const queue = new TaskQueue(); queue.enqueue(task()); expect(queue.claim("runtime-a", 60_000, 2_000)).not.toBeNull(); expect(queue.claim("runtime-b", 60_000, 2_001)).toBeNull(); });
  test("expired leases requeue and late owners cannot heartbeat", () => { const queue = new TaskQueue(); queue.enqueue(task()); const first = queue.claim("runtime-a", 5_000, 2_000)!; const second = queue.claim("runtime-b", 5_000, 7_001)!; expect(second.lease.ownerId).toBe("runtime-b"); expect(() => queue.heartbeat(first.task.taskId, "runtime-a", first.lease.token, 5_000, 7_002)).toThrow(); });
  test("completion requires a real HTTPS URL", () => { const queue = new TaskQueue(); queue.enqueue(task()); const claim = queue.claim("runtime", 5_000, 2_000)!; expect(() => queue.finish(claim.task.taskId, "runtime", claim.lease.token, [], 2_100)).toThrow(); expect(queue.finish(claim.task.taskId, "runtime", claim.lease.token, ["https://github.com/desync-organization/helios/issues/7#issuecomment-1"], 2_100).status).toBe("done"); });
  test("event stream enforces a monotonic per-run sequence", () => { const feed = new CanonicalEventFeed(); const first = trace(); feed.append(first); expect(() => feed.append(trace(3, { runId: first.runId }))).toThrow(); expect(feed.append(trace(2, { runId: first.runId })).duplicate).toBeFalse(); expect(feed.page(first.runId).nextCursor).toBe(2); });
  test("event IDs deduplicate exactly once", () => { const feed = new CanonicalEventFeed(); const event = trace(); feed.append(event); expect(feed.append(event).duplicate).toBeTrue(); });
  test("retention deletes payloads but preserves immutable audit facts", () => { const result = applyRetention<Array<{ id: string; expiresAt: number; immutableAudit?: boolean; payload?: unknown; searchableProjection?: string }>[number]>([{ id: "memory", expiresAt: 1, payload: "private", searchableProjection: "private" }, { id: "audit", expiresAt: 1, immutableAudit: true, payload: "private", searchableProjection: "private" }], 2); expect(result.deletedIds).toEqual(["memory", "audit"]); expect(result.retained).toEqual([{ id: "audit", expiresAt: 1, immutableAudit: true, payload: undefined, searchableProjection: undefined }]); });
  test("adapter promotion and rollback are atomic", () => { const registry = new AdapterRegistry(); const adapterId = newId("adapter"); registry.register({ schemaVersion: 1, adapterId, version: "v1", baseModel: "Qwen3-4B", baseRevision: "r1", baseSha256: SHA256, tokenizerSha256: SHA256, adapterSha256: SHA256, trainingRunId: "training-1", datasetManifestSha256: SHA256, evalReportSha256: SHA256, heldOutEvalRunId: newId("evalRun"), tenRunBenchmarkPassed: true, stableGauntletRuns: [newId("evalRun"), newId("evalRun"), newId("evalRun")], safetySubgroupsPassed: true, qualityApprovedBy: "member-3", compatibilityApprovedBy: "member-1", activeRoles: ["triage", "docs"], status: "approved", createdAt: 1 }); expect(registry.activate(adapterId).triage).toBe(adapterId); expect(registry.rollback(adapterId).triage).toBeUndefined(); });
  test("failed gates cannot activate an adapter", () => { const registry = new AdapterRegistry(); const adapterId = newId("adapter"); registry.register({ schemaVersion: 1, adapterId, version: "v1", baseModel: "Qwen", baseRevision: "r", baseSha256: SHA256, tokenizerSha256: SHA256, adapterSha256: SHA256, trainingRunId: "t", datasetManifestSha256: SHA256, evalReportSha256: SHA256, heldOutEvalRunId: newId("evalRun"), tenRunBenchmarkPassed: false, stableGauntletRuns: [newId("evalRun"), newId("evalRun"), newId("evalRun")], safetySubgroupsPassed: true, qualityApprovedBy: "m3", compatibilityApprovedBy: "m1", activeRoles: ["triage"], status: "candidate", createdAt: 1 }); expect(() => registry.activate(adapterId)).toThrow(); });
  test("operational alerts are durable text and deduplicated per window", () => { const engine = new AlertEngine(); const signal = { kind: "lease_expiry" as const, severity: "warning" as const, messageRedacted: "Lease expired for a task", ruleId: "alert.lease", repo: "desync-organization/helios" }; expect(engine.emit(signal, 60_000)).not.toBeNull(); expect(engine.emit(signal, 60_001)).toBeNull(); expect(engine.list()).toHaveLength(1); });
});
