import { httpRouter } from "convex/server";
import { httpAction } from "./_generated/server";
import { internal } from "./_generated/api";

const http = httpRouter();

function json(value: unknown, status = 200, headers?: HeadersInit): Response { return Response.json(value, { status, headers }); }
function error(status: number, code: string, message: string, retryable = false, headers?: HeadersInit): Response { return json({ error: { code, message, retryable } }, status, headers); }
function constantTimeEqual(left: string, right: string): boolean { const length = Math.max(left.length, right.length, 1); let difference = left.length ^ right.length; for (let i = 0; i < length; i += 1) difference |= (left.charCodeAt(i) || 0) ^ (right.charCodeAt(i) || 0); return difference === 0; }
function authorized(request: Request, name: "CONTROL_PLANE_INGEST_TOKEN" | "RUNTIME_BEARER_TOKEN"): boolean { const expected = process.env[name] ?? ""; const header = request.headers.get("Authorization") ?? ""; return expected.length >= 32 && header.startsWith("Bearer ") && constantTimeEqual(header.slice(7), expected); }
async function body(request: Request, maximumBytes = 512_000): Promise<any> { const declared = Number(request.headers.get("Content-Length") ?? "0"); if (declared > maximumBytes) throw new RangeError("TOO_LARGE"); const raw = await request.arrayBuffer(); if (raw.byteLength > maximumBytes) throw new RangeError("TOO_LARGE"); return JSON.parse(new TextDecoder().decode(raw)); }
async function sha256(value: string): Promise<string> { const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function newDomainId(prefix: string): string { return `${prefix}_${crypto.randomUUID().replaceAll("-", "").slice(0, 26).toUpperCase()}`; }
function domainProjection<T>(value: T): T { return JSON.parse(JSON.stringify(value, (key, item) => ["_id", "_creationTime", "leaseTokenHash", "installationId", "githubRepositoryId"].includes(key) ? undefined : item)) as T; }
function route(path: string, method: "GET" | "POST", handler: Parameters<typeof http.route>[0]["handler"]): void { http.route({ path, method, handler }); }

route("/ingest/github", "POST", httpAction(async (ctx, request) => {
  if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token");
  try { const webhook = await body(request, 2_000_000); if (webhook.schemaVersion !== 1) return error(422, "SCHEMA_VERSION", "Unsupported schema version"); return json(await ctx.runMutation(internal.ingest.github, { webhook, taskId: newDomainId("tsk"), now: Date.now() }), 202); } catch (cause) { return cause instanceof RangeError ? error(413, "TOO_LARGE", "Payload exceeds limit") : error(422, "VALIDATION_FAILED", "Invalid webhook payload"); }
}));
route("/ingest/dead-letter", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { return json(await ctx.runMutation(internal.ingest.deadLetter, { record: await body(request) }), 202); } catch { return error(422, "VALIDATION_FAILED", "Invalid dead-letter payload"); } }));

route("/runtime/claim", "POST", httpAction(async (ctx, request) => {
  if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token");
  try { const input = await body(request); const leaseToken = `${crypto.randomUUID()}${crypto.randomUUID()}`; const claimed = await ctx.runMutation(internal.tasks.claim, { ownerId: input.ownerId, leaseMs: input.leaseMs ?? 60_000, leaseTokenHash: await sha256(leaseToken), now: Date.now() }); if (!claimed) return json({ task: null }, 200); const repository = await ctx.runQuery(internal.repositories.getRedacted, { repo: claimed.repo }); return json({ task: domainProjection(claimed), lease: { token: leaseToken, ownerId: input.ownerId, expiresAt: claimed.leaseExpiresAt }, repository: domainProjection(repository), memoryPack: domainProjection(await ctx.runQuery(internal.memory.pack, { repo: claimed.repo, now: Date.now(), limit: 50 })) }); } catch { return error(422, "VALIDATION_FAILED", "Invalid claim request"); }
}));
route("/runtime/heartbeat", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const result = await ctx.runMutation(internal.tasks.heartbeat, { taskId: input.taskId, ownerId: input.ownerId, leaseTokenHash: await sha256(input.leaseToken), extensionMs: input.extensionMs ?? 60_000, now: Date.now() }); return result.ok ? json(result) : error(409, result.reason ?? "LOST_LEASE", "Lease is no longer current"); } catch { return error(422, "VALIDATION_FAILED", "Invalid heartbeat request"); } }));
route("/runtime/run/start", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); return json(await ctx.runMutation(internal.runtime.startRun, { run: input }), 202); } catch { return error(422, "VALIDATION_FAILED", "Invalid run"); } }));
route("/runtime/span", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const result = await ctx.runMutation(internal.runtime.appendSpan, { span: input, feedEvent: { eventId: input.eventId, runId: input.runId, taskId: input.taskId, sequence: input.sequence, kind: "span", label: input.label ?? "live", projectionRedacted: input.projectionRedacted ?? { nodeId: input.nodeId, agent: input.agent, status: input.status, tokensIn: input.tokensIn, tokensOut: input.tokensOut, costUsd: input.costUsd, costCloudEquivalentUsd: input.costCloudEquivalentUsd, executionLocation: input.executionLocation }, createdAt: Date.now() } }); return result.conflict ? error(409, "SEQUENCE_CONFLICT", `Expected sequence ${result.expectedSequence}`) : json(result, 202); } catch { return error(422, "VALIDATION_FAILED", "Invalid span"); } }));
route("/runtime/artifact", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request, 1_000_000); if (typeof input.content === "string" && /gh[pousr]_[A-Za-z0-9]{20,}|BEGIN .*PRIVATE KEY|(?:AKIA|ASIA)[A-Z0-9]{16}/i.test(input.content)) return error(422, "RAW_SECRET_REJECTED", "Artifact contains secret-like material"); const { content, ...metadata } = input; const artifact = { ...metadata, contentRedacted: content, searchableProjection: String(content ?? "").slice(0, 8_192) }; return json(await ctx.runMutation(internal.runtime.putArtifact, { artifact }), 202); } catch (cause) { return cause instanceof RangeError ? error(413, "TOO_LARGE", "Artifact exceeds limit") : error(422, "VALIDATION_FAILED", "Invalid artifact"); } }));
route("/runtime/run/finish", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const lease = await ctx.runMutation(internal.tasks.finish, { taskId: input.taskId, ownerId: input.ownerId, leaseTokenHash: await sha256(input.leaseToken), status: input.taskStatus, resultUrls: input.resultUrls ?? [], error: input.error, now: Date.now() }); if (!lease.ok) return error(lease.reason === "LOST_LEASE" ? 409 : 422, lease.reason ?? "FINISH_REJECTED", "Run completion rejected"); const run = await ctx.runMutation(internal.runtime.finishRun, { runId: input.runId, patch: input.run }); return run.ok ? json(run) : error(422, run.reason ?? "RUN_FINISH_REJECTED", "Run completion rejected"); } catch { return error(422, "VALIDATION_FAILED", "Invalid finish request"); } }));
route("/runtime/task/escalate", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const result = await ctx.runMutation(internal.tasks.finish, { taskId: input.taskId, ownerId: input.ownerId, leaseTokenHash: await sha256(input.leaseToken), status: "escalated", resultUrls: input.resultUrls ?? [], error: input.error, now: Date.now() }); return result.ok ? json(result) : error(409, result.reason ?? "ESCALATION_REJECTED", "Escalation rejected"); } catch { return error(422, "VALIDATION_FAILED", "Invalid escalation request"); } }));
route("/runtime/security/findings", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const result = await ctx.runMutation(internal.security.upsertFinding, { finding: input, now: Date.now() }); return result.ok ? json(result, 202) : error(422, result.reason ?? "FINDING_REJECTED", "Finding rejected"); } catch { return error(422, "VALIDATION_FAILED", "Invalid finding"); } }));
route("/runtime/control", "GET", httpAction(async (ctx, request) => authorized(request, "CONTROL_PLANE_INGEST_TOKEN") ? json(domainProjection(await ctx.runQuery(internal.controls.get, {}))) : error(401, "UNAUTHENTICATED", "Invalid bearer token")));
route("/runtime/config/agents", "GET", httpAction(async (ctx, request) => authorized(request, "CONTROL_PLANE_INGEST_TOKEN") ? json(domainProjection({ agents: await ctx.runQuery(internal.agents.listActive, {}), adapters: await ctx.runQuery(internal.adapters.activePointers, {}) })) : error(401, "UNAUTHENTICATED", "Invalid bearer token")));

route("/providers/authorize", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); return json(await ctx.runQuery(internal.providers.authorize, { taskId: input.taskId, repo: input.repo, purpose: input.purpose, requestedProvider: input.requestedProvider, now: Date.now() })); } catch { return error(422, "VALIDATION_FAILED", "Invalid authorization request"); } }));
route("/providers/audit", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const usage = input.tokens ?? {}; const call = { providerCallId: newDomainId("prc"), taskId: input.taskId, repo: input.repo, provider: input.provider, model: input.exactModel ?? input.model ?? "unknown", purpose: input.purpose, consentRef: input.consentRef, classification: input.classification, bytesSent: input.bytesSent, tokensIn: input.tokensIn ?? usage.prompt_tokens ?? 0, tokensOut: input.tokensOut ?? usage.completion_tokens ?? 0, latencyMs: input.latencyMs ?? 0, costUsd: input.costUsd ?? 0, executionLocation: input.executionLocation ?? "remote_provider", requestId: input.requestId, status: input.status ?? "completed", createdAt: input.createdAt ?? Date.now() }; return json(await ctx.runMutation(internal.providers.record, { call }), 202); } catch { return error(422, "VALIDATION_FAILED", "Invalid provider audit"); } }));
route("/writeback/reserve", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request, 2_500_000); const result = await ctx.runMutation(internal.writeback.reserve, { intent: input.intent, leaseTokenHash: await sha256(input.leaseToken), now: Date.now() }); return result.ok ? json(result) : error(result.reason === "LOST_LEASE" || result.reason === "IN_PROGRESS" ? 409 : 403, result.reason ?? "DENIED", "Write-back authorization denied"); } catch (cause) { return cause instanceof RangeError ? error(413, "TOO_LARGE", "Write-back exceeds limit") : error(422, "VALIDATION_FAILED", "Invalid write-back"); } }));
route("/writeback/complete", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); const result = await ctx.runMutation(internal.writeback.complete, { ...input, now: Date.now() }); return result.ok ? json(result) : error(409, result.reason ?? "COMPLETION_REJECTED", "Write-back completion rejected"); } catch { return error(422, "VALIDATION_FAILED", "Invalid completion"); } }));
route("/writeback/fail", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const input = await body(request); return json(await ctx.runMutation(internal.writeback.fail, { writebackId: input.writebackId, error: input.error, now: Date.now() })); } catch { return error(422, "VALIDATION_FAILED", "Invalid failure record"); } }));
route("/maintenance/retry-dead-letters", "POST", httpAction(async (ctx, request) => {
  if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token");
  const now = Date.now();
  const due = await ctx.runQuery(internal.ingest.dueDeadLetters, { now, limit: 25 });
  const results = [];
  for (const item of due) results.push(await ctx.runMutation(internal.ingest.retryOne, { deliveryId: item.deliveryId, taskId: newDomainId("tsk"), now }));
  return json({ attempted: due.length, recovered: results.filter((result) => result.ok).length }, 202);
}));
route("/admin/repositories/upsert", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { const repository = await body(request); return json({ id: await ctx.runMutation(internal.repositories.upsert, { repository: { ...repository, updatedAt: Date.now() } }) }); } catch { return error(422, "VALIDATION_FAILED", "Invalid repository descriptor"); } }));
route("/admin/control", "POST", httpAction(async (ctx, request) => { if (!authorized(request, "CONTROL_PLANE_INGEST_TOKEN")) return error(401, "UNAUTHENTICATED", "Invalid bearer token"); try { return json(await ctx.runMutation(internal.controls.update, { patch: await body(request), now: Date.now() })); } catch { return error(422, "VALIDATION_FAILED", "Invalid control state"); } }));

export default http;
