import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const optionalError = v.optional(v.object({ code: v.string(), message: v.string(), retryable: v.boolean() }));

export default defineSchema({
  tasks: defineTable({ taskId: v.string(), source: v.any(), mode: v.string(), type: v.string(), repo: v.string(), payloadRedacted: v.string(), status: v.string(), dedupeKey: v.string(), requestedBy: v.string(), consentScope: v.any(), dataClassification: v.string(), policyVersion: v.string(), approvedBacklogBatchId: v.optional(v.string()), leaseOwnerId: v.optional(v.string()), leaseTokenHash: v.optional(v.string()), leaseAcquiredAt: v.optional(v.number()), leaseHeartbeatAt: v.optional(v.number()), leaseExpiresAt: v.optional(v.number()), resultUrls: v.array(v.string()), error: optionalError, createdAt: v.number(), updatedAt: v.number() })
    .index("by_task_id", ["taskId"]).index("by_status_created", ["status", "createdAt"]).index("by_repo_status", ["repo", "status"]).index("by_mode_type", ["mode", "type"]).index("by_repo_dedupe", ["repo", "dedupeKey"]).index("by_updated", ["updatedAt"]),
  runs: defineTable({ runId: v.string(), taskId: v.string(), mode: v.string(), repo: v.string(), lane: v.string(), status: v.string(), plannerConfidence: v.number(), planArtifactId: v.optional(v.string()), startedAt: v.number(), finishedAt: v.optional(v.number()), tokensIn: v.number(), tokensOut: v.number(), costUsd: v.number(), costCloudEquivalentUsd: v.number(), latencyMs: v.optional(v.number()), agentVersions: v.array(v.string()), adapterVersions: v.array(v.string()), fallbackFlags: v.array(v.string()), resultUrls: v.array(v.string()), dataEgressSummary: v.any(), error: optionalError })
    .index("by_run_id", ["runId"]).index("by_task", ["taskId"]).index("by_repo_status", ["repo", "status"]).index("by_mode_status", ["mode", "status"]).index("by_started", ["startedAt"]),
  spans: defineTable({ spanId: v.string(), eventId: v.string(), sequence: v.number(), runId: v.string(), taskId: v.string(), parentSpanId: v.optional(v.string()), nodeId: v.string(), agent: v.string(), agentVersion: v.string(), model: v.string(), baseRevision: v.string(), baseSha256: v.string(), quantization: v.string(), promptHash: v.string(), adapterId: v.optional(v.string()), adapterVersion: v.optional(v.string()), adapterHash: v.optional(v.string()), inputArtifactRefs: v.array(v.string()), outputArtifactRef: v.optional(v.string()), tokensIn: v.number(), tokensOut: v.number(), costUsd: v.number(), costCloudEquivalentUsd: v.number(), latencyMs: v.number(), toolCalls: v.any(), executionLocation: v.string(), fallback: v.boolean(), status: v.string(), verdict: v.optional(v.string()), error: optionalError, startedAt: v.number(), finishedAt: v.optional(v.number()) })
    .index("by_span_id", ["spanId"]).index("by_event_id", ["eventId"]).index("by_run_sequence", ["runId", "sequence"]).index("by_run", ["runId"]).index("by_parent", ["parentSpanId"]).index("by_agent_started", ["agent", "startedAt"]).index("by_model_adapter", ["model", "adapterId"]).index("by_status_started", ["status", "startedAt"]),
  artifacts: defineTable({ artifactId: v.string(), schemaVersion: v.number(), taskId: v.string(), runId: v.string(), nodeId: v.string(), type: v.string(), producer: v.any(), upstreamArtifactIds: v.array(v.string()), policyRuleIds: v.array(v.string()), contentHash: v.string(), contentRef: v.optional(v.string()), contentRedacted: v.optional(v.string()), searchableProjection: v.string(), retentionClass: v.string(), createdAt: v.number() })
    .index("by_artifact_id", ["artifactId"]).index("by_task", ["taskId"]).index("by_run", ["runId"]).index("by_run_type", ["runId", "type"]).index("by_content_hash", ["contentHash"]).index("by_created", ["createdAt"]),
  agents: defineTable({ agentId: v.string(), name: v.string(), version: v.string(), origin: v.string(), role: v.string(), personaHash: v.string(), toolGrants: v.array(v.string()), modelIdentity: v.any(), activeAdapterId: v.optional(v.string()), immutable: v.boolean(), createdAt: v.number() })
    .index("by_agent_id", ["agentId"]).index("by_name_version", ["name", "version"]).index("by_role", ["role"]).index("by_origin", ["origin"]),
  adapters: defineTable({ adapterId: v.string(), version: v.string(), baseModel: v.string(), baseRevision: v.string(), baseSha256: v.string(), tokenizerSha256: v.string(), adapterSha256: v.string(), trainingRunId: v.string(), datasetManifestSha256: v.string(), evalReportSha256: v.string(), heldOutEvalRunId: v.string(), tenRunBenchmarkPassed: v.boolean(), stableGauntletRuns: v.array(v.string()), safetySubgroupsPassed: v.boolean(), qualityApprovedBy: v.string(), compatibilityApprovedBy: v.string(), activeRoles: v.array(v.string()), rollbackPredecessorId: v.optional(v.string()), status: v.string(), createdAt: v.number(), updatedAt: v.number() })
    .index("by_adapter_id", ["adapterId"]).index("by_status", ["status"]).index("by_base", ["baseModel", "baseSha256"]),
  repositories: defineTable({ repo: v.string(), githubRepositoryId: v.string(), installationId: v.string(), defaultBranch: v.string(), visibility: v.string(), writebackOptIn: v.boolean(), securityAuditOptIn: v.boolean(), allowedActions: v.array(v.string()), allowedCloudProviders: v.array(v.string()), protectedPaths: v.array(v.string()), sizeLimits: v.any(), requiredChecks: v.array(v.string()), activePolicyVersion: v.string(), retentionPolicy: v.any(), lastWebhookAt: v.optional(v.number()), health: v.string(), updatedAt: v.number() })
    .index("by_repo", ["repo"]).index("by_github_id", ["githubRepositoryId"]).index("by_installation", ["installationId"]).index("by_health", ["health"]),
  entities: defineTable({ entityId: v.string(), repo: v.string(), layer: v.string(), kind: v.string(), externalKey: v.string(), summaryRedacted: v.string(), sourceTaskIds: v.array(v.string()), retentionClass: v.string(), expiresAt: v.number(), createdAt: v.number(), updatedAt: v.number() })
    .index("by_entity_id", ["entityId"]).index("by_repo_kind_key", ["repo", "kind", "externalKey"]).index("by_repo_layer", ["repo", "layer"]).index("by_expiry", ["expiresAt"]),
  policies: defineTable({ policyId: v.string(), repo: v.string(), name: v.string(), version: v.string(), rules: v.any(), gitCommitSha: v.string(), active: v.boolean(), createdAt: v.number(), activatedAt: v.optional(v.number()) })
    .index("by_policy_id", ["policyId"]).index("by_repo_name_version", ["repo", "name", "version"]).index("by_repo_active", ["repo", "active"]),
  evalCases: defineTable({ evalCaseId: v.string(), mode: v.string(), status: v.string(), trigger: v.string(), inputRedacted: v.string(), wrongOutputRedacted: v.string(), correctionRedacted: v.optional(v.string()), sourceUrl: v.optional(v.string()), versionFingerprint: v.string(), createdAt: v.number(), updatedAt: v.number() })
    .index("by_eval_case_id", ["evalCaseId"]).index("by_status_mode", ["status", "mode"]).index("by_trigger", ["trigger"]),
  evalRuns: defineTable({ evalRunId: v.string(), mode: v.string(), configurationVersion: v.string(), reportSha256: v.string(), score: v.number(), thresholds: v.any(), passed: v.boolean(), secretLeakCount: v.number(), unauthorizedActionCount: v.number(), reportRef: v.optional(v.string()), createdAt: v.number() })
    .index("by_eval_run_id", ["evalRunId"]).index("by_mode_created", ["mode", "createdAt"]).index("by_config", ["configurationVersion"]),
  alertRules: defineTable({ ruleId: v.string(), kind: v.string(), enabled: v.boolean(), severity: v.string(), parameters: v.any(), version: v.string(), updatedAt: v.number() })
    .index("by_rule_id", ["ruleId"]).index("by_kind_enabled", ["kind", "enabled"]),
  alertEvents: defineTable({ alertId: v.string(), kind: v.string(), severity: v.string(), repo: v.optional(v.string()), taskId: v.optional(v.string()), runId: v.optional(v.string()), messageRedacted: v.string(), ruleId: v.string(), acknowledgedAt: v.optional(v.number()), createdAt: v.number() })
    .index("by_alert_id", ["alertId"]).index("by_kind_created", ["kind", "createdAt"]).index("by_repo_created", ["repo", "createdAt"]).index("by_acknowledged", ["acknowledgedAt"]),
  reviewItems: defineTable({ reviewItemId: v.string(), repo: v.string(), taskId: v.string(), runId: v.optional(v.string()), kind: v.string(), restricted: v.boolean(), status: v.string(), reasonRedacted: v.string(), artifactIds: v.array(v.string()), createdAt: v.number(), updatedAt: v.number() })
    .index("by_review_id", ["reviewItemId"]).index("by_status_created", ["status", "createdAt"]).index("by_repo_status", ["repo", "status"]),
  writebackActions: defineTable({ writebackId: v.string(), taskId: v.string(), runId: v.string(), repo: v.string(), action: v.string(), idempotencyKey: v.string(), artifactId: v.string(), artifactHash: v.string(), criticArtifactId: v.string(), policyDecision: v.any(), status: v.string(), resultUrl: v.optional(v.string()), externalId: v.optional(v.string()), error: optionalError, createdAt: v.number(), updatedAt: v.number() })
    .index("by_writeback_id", ["writebackId"]).index("by_repo_idempotency", ["repo", "idempotencyKey"]).index("by_task", ["taskId"]).index("by_status_updated", ["status", "updatedAt"]),
  approvedBacklogBatches: defineTable({ batchId: v.string(), repo: v.string(), issueUrls: v.array(v.string()), approvedBy: v.string(), expiresAt: v.number(), status: v.string(), createdAt: v.number() })
    .index("by_batch_id", ["batchId"]).index("by_repo_status", ["repo", "status"]).index("by_expiry", ["expiresAt"]),
  securityFindings: defineTable({ findingId: v.string(), repo: v.string(), fingerprint: v.string(), scanner: v.string(), scannerVersion: v.string(), ruleId: v.string(), category: v.string(), severity: v.string(), confidence: v.string(), cwe: v.optional(v.string()), cve: v.optional(v.string()), advisoryUrls: v.array(v.string()), advisoryRetrievedAt: v.optional(v.number()), commitSha: v.string(), path: v.optional(v.string()), startLine: v.optional(v.number()), endLine: v.optional(v.number()), evidenceRedacted: v.string(), exploitability: v.string(), reachability: v.string(), falsePositiveReason: v.optional(v.string()), recommendedFix: v.string(), status: v.string(), restricted: v.boolean(), createdAt: v.number(), updatedAt: v.number() })
    .index("by_finding_id", ["findingId"]).index("by_repo_fingerprint", ["repo", "fingerprint"]).index("by_repo_status", ["repo", "status"]).index("by_severity_status", ["severity", "status"]).index("by_scanner", ["scanner"]),
  scanRuns: defineTable({ scanId: v.string(), repo: v.string(), commitSha: v.string(), kind: v.string(), toolVersions: v.any(), configurationHash: v.string(), exclusions: v.array(v.string()), readOnly: v.boolean(), status: v.string(), findingCount: v.number(), rawOutputRef: v.optional(v.string()), rawOutputExpiresAt: v.optional(v.number()), startedAt: v.number(), finishedAt: v.optional(v.number()), error: optionalError })
    .index("by_scan_id", ["scanId"]).index("by_repo_started", ["repo", "startedAt"]).index("by_status_started", ["status", "startedAt"]),
  sbomRefs: defineTable({ sbomId: v.string(), repo: v.string(), commitSha: v.string(), format: v.string(), objectRef: v.string(), sha256: v.string(), componentCount: v.number(), createdAt: v.number() })
    .index("by_sbom_id", ["sbomId"]).index("by_repo_commit", ["repo", "commitSha"]).index("by_sha", ["sha256"]),
  adapterPromotions: defineTable({ promotionId: v.string(), adapterId: v.string(), action: v.string(), roles: v.array(v.string()), predecessorByRole: v.any(), approvedBy: v.string(), reason: v.string(), createdAt: v.number() })
    .index("by_promotion_id", ["promotionId"]).index("by_adapter_created", ["adapterId", "createdAt"]).index("by_action", ["action"]),
  providerCalls: defineTable({ providerCallId: v.string(), taskId: v.string(), repo: v.string(), provider: v.string(), model: v.string(), purpose: v.string(), consentRef: v.string(), classification: v.string(), bytesSent: v.number(), tokensIn: v.number(), tokensOut: v.number(), latencyMs: v.number(), costUsd: v.number(), executionLocation: v.string(), requestId: v.string(), status: v.string(), errorCode: v.optional(v.string()), createdAt: v.number() })
    .index("by_provider_call_id", ["providerCallId"]).index("by_request_id", ["requestId"]).index("by_task", ["taskId"]).index("by_repo_created", ["repo", "createdAt"]).index("by_provider_created", ["provider", "createdAt"]),
  systemState: defineTable({ key: v.string(), globalPaused: v.boolean(), emergencyMode: v.boolean(), pausedAgents: v.array(v.string()), writebackMode: v.string(), securityScanMode: v.string(), currentAgentTag: v.string(), currentAdapterPointers: v.any(), updatedAt: v.number() }).index("by_key", ["key"]),
  webhookDeliveries: defineTable({ deliveryId: v.string(), event: v.string(), action: v.string(), repo: v.string(), status: v.string(), taskId: v.optional(v.string()), receivedAt: v.number(), updatedAt: v.number() }).index("by_delivery_id", ["deliveryId"]).index("by_repo_received", ["repo", "receivedAt"]).index("by_status", ["status"]),
  eventFeed: defineTable({ eventId: v.string(), runId: v.string(), taskId: v.string(), sequence: v.number(), kind: v.string(), label: v.string(), projectionRedacted: v.any(), createdAt: v.number() }).index("by_event_id", ["eventId"]).index("by_run_sequence", ["runId", "sequence"]).index("by_task_created", ["taskId", "createdAt"]),
  deadLetters: defineTable({ deliveryId: v.string(), repo: v.string(), event: v.string(), reason: v.string(), payloadRedacted: v.string(), normalized: v.optional(v.any()), attempts: v.number(), nextAttemptAt: v.number(), resolvedAt: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_delivery_id", ["deliveryId"]).index("by_retry", ["resolvedAt", "nextAttemptAt"]).index("by_repo_created", ["repo", "createdAt"]),
});
